name: Unicorn
on: [push, pull_request]
jobs:
  test:
    name: Test all
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: ["1.15"]
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Lint code base
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
        continue-on-error: true
